import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Providers from '@/components/Providers'
import Layout from '@/sections/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`h-screen w-full flex items-center justify-center ${inter.className}`}>
        <Providers>
          <Layout>
            {children}
          </Layout>
        </Providers>
        </body>
    </html>
  )
}
